### PR TITLE
Update Decentralized-Autonomous-Organizations.md

### PR DESCRIPTION
**Pull request by jivnshet**
Creates confusion while mention the ABI and Address of the contracts

### CODE REVIEW

**Review by yanukadeneth99 — CHANGES_REQUESTED** [review]
Hi @jivnshet, there is a sentence below the code that says : 

`Replace the contract address and ABI values with your relevant contract addresses and ABIs.`. 

If it seems too confusing, maybe you can change that up to something that makes more sense.

**Comment by ljcutts** [comment]
Hello @jivnshet . If you're going to do this, can you also include this explanation for the DAO ABI and address. Also, try to make the explanation of this as short and straight forward as possible?

**Comment by jivnshet** [comment]
Was facing issues to understand about which ABI address to enter into.

**Comment by ljcutts** [comment]
> Was facing issues to understand about which ABI address to enter into.

I understand. Just try not to make sure your explanation isn't too big and make sure that you also include the DAO ABI and Address in your explanation.

**Comment by yanukadeneth99** [comment]
Hey @jivnshet, do you need any help in this PR?

**Comment by jivnshet** [comment]
Hi @yanukadeneth99, presently no. Thanks!

**Comment by yanukadeneth99** [comment]
Closing for inactivity. Mention me if you want to re-open this.

**Pull request closed without merging**
