### PR TITLE
enable owner to withdraw via frontend & participate in mint

### PR DESCRIPTION
**Pull request by devdacian**
adds a separate withdraw button so owner can withdraw and also participate in the claim/mint; CryptoDevToken.withdraw() returns an error if balance is 0, front-end withdrawCoins() catches & shows it to user. useEffect() when walletConnected now calls getOwner()

### CODE REVIEW

**Comment by mr-stegosaurus** [comment]
i was going to propose this as well but looks like you've already started. i think the withdraw button is in the wrong spot, shouldn't the withdraw button render outside of the claim check? otherwise, you can only present the withdraw button if the owner has NFTs and tokens to claim that haven't been already

  const renderWithdrawButton = () => {
        // if owner is connected, withdrawCoins() is called
        if (walletConnected && isOwner) {
          return (
            <div>
              <div className={styles.description}>
             Contract holds X ether to withdraw!
              </div>
              <button className={styles.button1} onClick={withdrawCoins}>
                Withdraw Coins
              </button>
            </div>
          );
        };
  };  const renderWithdrawButton = () => {
        // if owner is connected, withdrawCoins() is called
        if (walletConnected && isOwner) {
          return (
            <div>
              <div className={styles.description}>
             Contract holds X ether to withdraw!
              </div>
              <button className={styles.button1} onClick={withdrawCoins}>
                Withdraw Coins
              </button>
            </div>
          );
        };
  };

**Comment by ljcutts** [comment]
Hello @devdacian. These are nice suggestions. Can you edit the CSS for the Withdraw Coins button and make it similar to the mint tokens button.  Also make the style name for the withdraw button more unique versus saying styles.button1.

Also in this code here in the pages/index.js
```typescript
 { isWalletConnected && isOwner ? (
                <div>
                  {loading ? (
                    <button className={styles.button}>Loading...</button>
                  ) : (
                    <button className={styles.button1} onClick={withdrawCoins}>
                      Withdraw Coins
                    </button>
                  )}
                </div>
              ) : (
                ""
              )}
```

The isWalletConnected isn't necessary as the ternary operation outside of that is already checking to see if this is true.

Once you make these changes, I will merge this into the codebase.

**Comment by devdacian** [comment]
Hi @ljcutts 

Thank you for the feedback; I've removed the unnecessary isWalletConnected check & had fixed the mis-typed extra '1' in the button style, such that it now simply matches the style of the other buttons

**Comment by ljcutts** [comment]
@devdacian Thank you! Your suggestions have been merged!

**Pull request merged**
